/**
 * Tailwind class groups for exam cards — keyed by ENTRANCE_EXAMS[].accent
 */
export const EXAM_ACCENT_CLASSES = {
  blue: {
    strip: 'border-t-4 border-blue-500',
    selected: 'ring-2 ring-blue-200 border-blue-200',
    button: 'bg-blue-600 hover:bg-blue-700 text-white',
    leftStrip: 'border-l-4 border-blue-500',
    badge: 'bg-blue-50 text-blue-700',
    headerBg: 'bg-gradient-to-r from-blue-50 to-blue-100/60',
    headerText: 'text-blue-900',
    headerSub: 'text-blue-600',
    ring: 'ring-blue-100',
    divider: 'border-blue-200',
    indexBg: 'bg-blue-50 text-blue-600',
  },
  indigo: {
    strip: 'border-t-4 border-indigo-500',
    selected: 'ring-2 ring-indigo-200 border-indigo-200',
    button: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    leftStrip: 'border-l-4 border-indigo-500',
    badge: 'bg-indigo-50 text-indigo-700',
    headerBg: 'bg-gradient-to-r from-indigo-50 to-indigo-100/60',
    headerText: 'text-indigo-900',
    headerSub: 'text-indigo-600',
    ring: 'ring-indigo-100',
    divider: 'border-indigo-200',
    indexBg: 'bg-indigo-50 text-indigo-600',
  },
  teal: {
    strip: 'border-t-4 border-teal-500',
    selected: 'ring-2 ring-teal-200 border-teal-200',
    button: 'bg-teal-600 hover:bg-teal-700 text-white',
    leftStrip: 'border-l-4 border-teal-500',
    badge: 'bg-teal-50 text-teal-700',
    headerBg: 'bg-gradient-to-r from-teal-50 to-teal-100/60',
    headerText: 'text-teal-900',
    headerSub: 'text-teal-600',
    ring: 'ring-teal-100',
    divider: 'border-teal-200',
    indexBg: 'bg-teal-50 text-teal-600',
  },
  green: {
    strip: 'border-t-4 border-emerald-500',
    selected: 'ring-2 ring-emerald-200 border-emerald-200',
    button: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    leftStrip: 'border-l-4 border-emerald-500',
    badge: 'bg-emerald-50 text-emerald-700',
    headerBg: 'bg-gradient-to-r from-emerald-50 to-emerald-100/60',
    headerText: 'text-emerald-900',
    headerSub: 'text-emerald-600',
    ring: 'ring-emerald-100',
    divider: 'border-emerald-200',
    indexBg: 'bg-emerald-50 text-emerald-600',
  },
  orange: {
    strip: 'border-t-4 border-orange-500',
    selected: 'ring-2 ring-orange-200 border-orange-200',
    button: 'bg-orange-600 hover:bg-orange-700 text-white',
    leftStrip: 'border-l-4 border-orange-500',
    badge: 'bg-orange-50 text-orange-700',
    headerBg: 'bg-gradient-to-r from-orange-50 to-orange-100/60',
    headerText: 'text-orange-900',
    headerSub: 'text-orange-600',
    ring: 'ring-orange-100',
    divider: 'border-orange-200',
    indexBg: 'bg-orange-50 text-orange-600',
  },
  purple: {
    strip: 'border-t-4 border-purple-500',
    selected: 'ring-2 ring-purple-200 border-purple-200',
    button: 'bg-purple-600 hover:bg-purple-700 text-white',
    leftStrip: 'border-l-4 border-purple-500',
    badge: 'bg-purple-50 text-purple-700',
    headerBg: 'bg-gradient-to-r from-purple-50 to-purple-100/60',
    headerText: 'text-purple-900',
    headerSub: 'text-purple-600',
    ring: 'ring-purple-100',
    divider: 'border-purple-200',
    indexBg: 'bg-purple-50 text-purple-600',
  },
  sky: {
    strip: 'border-t-4 border-sky-500',
    selected: 'ring-2 ring-sky-200 border-sky-200',
    button: 'bg-sky-600 hover:bg-sky-700 text-white',
    leftStrip: 'border-l-4 border-sky-500',
    badge: 'bg-sky-50 text-sky-800',
    headerBg: 'bg-gradient-to-r from-sky-50 to-cyan-100/50',
    headerText: 'text-sky-950',
    headerSub: 'text-sky-700',
    ring: 'ring-sky-100',
    divider: 'border-sky-200',
    indexBg: 'bg-sky-50 text-sky-700',
  },
};

export function getAccentClasses(accent) {
  return EXAM_ACCENT_CLASSES[accent] || EXAM_ACCENT_CLASSES.blue;
}
